config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :assertions, except: %i[edit update]
  resources :test_runs
  resources :prompts do
    member do
      get 'diff/:prompt_version_id', action: :diff, as: :diff
    end
  end

  resources :test_runs, except: %i[edit update destroy] do
    resources :test_model_version_runs, only: %i[show] do
      resources :jobs, controller: 'test_model_version_run_jobs', only: %i[create]
    end
  end

  resources :compare, only: [:index] do
    collection do
      get :model_versions
    end
  end

  resources :test_results, only: %i[index update show] do
    resources :assertion_results, only: %i[index]
  end

  resources :models do
    resources :model_versions
  end
  devise_for :users

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'dashboard#index'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index; end
end

app/views/dashboard/index.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid relative">
  <%= render 'layouts/flash' %>

  <h2
    class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200"
  >
    Dashboard
  </h2>
  <div class="absolute top-0 right-0 mt-4 mr-4">
    <%= link_to "New model", new_model_path, class: "flex items-center justify-between px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" %>
  </div>
  <!-- Cards -->
  <div class="grid gap-6 mb-8 md:grid-cols-2 xl:grid-cols-4">
    <!-- Card -->
    <div
      class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
    >
      <div
        class="p-3 mr-4 text-orange-500 bg-orange-100 rounded-full dark:text-orange-100 dark:bg-orange-500"
      >
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
          <path
            d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z"
          ></path>
        </svg>
      </div>
      <div>
        <p
          class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400"
        >
          Models
        </p>
        <p
          class="text-lg font-semibold text-gray-700 dark:text-gray-200"
        >
          <%= current_user.models.count %>
        </p>
      </div>
    </div>
    <!-- Card -->
    <div
      class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
    >
      <div
        class="p-3 mr-4 text-green-500 bg-green-100 rounded-full dark:text-green-100 dark:bg-green-500"
      >
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
          <path
            fill-rule="evenodd"
            d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </div>
      <div>
        <p
          class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400"
        >
          Prompts
        </p>
        <p
          class="text-lg font-semibold text-gray-700 dark:text-gray-200"
        >
          <%= link_to current_user.prompts.count, prompts_url, class: "text-blue-500 underline-link" %>
        </p>
      </div>
    </div>
    <!-- Card -->
    <div
      class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
    >
      <div
        class="p-3 mr-4 text-blue-500 bg-blue-100 rounded-full dark:text-blue-100 dark:bg-blue-500"
      >
       <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
          <path
            fill-rule="evenodd"
            d="M18 5v8a2 2 0 01-2 2h-5l-5 4v-4H4a2 2 0 01-2-2V5a2 2 0 012-2h12a2 2 0 012 2zM7 8H5v2h2V8zm2 0h2v2H9V8zm6 0h-2v2h2V8z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </div>
      <div>
        <p
          class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400"
        >
          Test results
        </p>
        <p
          class="text-lg font-semibold text-gray-700 dark:text-gray-200"
        >
           <%= link_to current_user.test_results.count, test_results_url, class: "text-blue-500 underline-link" %>
        </p>
      </div>
    </div>
     <div
      class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
    >
      <div
        class="p-3 mr-4 text-blue-500 bg-blue-100 rounded-full dark:text-blue-100 dark:bg-blue-500"
      >
       <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
          <path
            fill-rule="evenodd"
            d="M18 5v8a2 2 0 01-2 2h-5l-5 4v-4H4a2 2 0 01-2-2V5a2 2 0 012-2h12a2 2 0 012 2zM7 8H5v2h2V8zm2 0h2v2H9V8zm6 0h-2v2h2V8z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </div>
      <div>
        <p
          class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400"
        >
          Test runs
        </p>
        <p
          class="text-lg font-semibold text-gray-700 dark:text-gray-200"
        >
           <%= link_to current_user.test_runs.count, test_runs_url, class: "text-blue-500 underline-link" %>
        </p>
      </div>
    </div>
    <!-- Card -->
    <%# <div
      class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
    >
      <div
        class="p-3 mr-4 text-teal-500 bg-teal-100 rounded-full dark:text-teal-100 dark:bg-teal-500"
      >
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
          <path
            fill-rule="evenodd"
            d="M18 5v8a2 2 0 01-2 2h-5l-5 4v-4H4a2 2 0 01-2-2V5a2 2 0 012-2h12a2 2 0 012 2zM7 8H5v2h2V8zm2 0h2v2H9V8zm6 0h-2v2h2V8z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </div>
      <div>
        <p
          class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400"
        >
          Pending
        </p>
        <p
          class="text-lg font-semibold text-gray-700 dark:text-gray-200"
        >
          35
        </p>
      </div>
    </div> %>
  </div>

  <!-- New Table -->
  <div class="w-full overflow-hidden rounded-lg shadow-xs">
    <div class="w-full overflow-x-auto">
      <table class="w-full whitespace-no-wrap">
        <thead>
          <tr
            class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800"
          >
            <th class="px-4 py-3">Model</th>
            <th class="px-4 py-3">Created At</th>
          </tr>
        </thead>
        <tbody
          class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800"
        >
          <% if current_user.models.empty? %>
            <tr>
              <td colspan="2" class="px-4 py-3 text-center">
                <p class="text-gray-500">No models found.</p>
              </td>
            </tr>
          <% else %>
            <% current_user.models.each do |model| %>
              <tr class="text-gray-700 dark:text-gray-400">
                <td class="px-4 py-3">
                  <div class="flex items-center text-sm">
                    <div>
                      <p class="font-semibold"><%= link_to model.name, model, class: "text-blue-500 underline-link" %></p>
                    </div>
                  </div>
                </td>
                <td class="px-4 py-3 text-sm">
                  <%= model.created_at.to_date %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
    <div
      class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800"
    >
      <%# <span class="flex items-center col-span-3">
        Showing 1 of 10
      </span>
      <span class="col-span-2"></span> %>
      <!-- Pagination -->
      <%# <span class="flex col-span-4 mt-2 sm:mt-auto sm:justify-end">
        <nav aria-label="Table navigation">
          <ul class="inline-flex items-center">
            <li>
              <button
                class="px-3 py-1 rounded-md rounded-l-lg focus:outline-none focus:shadow-outline-purple"
                aria-label="Previous"
              >
                <svg
                  aria-hidden="true"
                  class="w-4 h-4 fill-current"
                  viewBox="0 0 20 20"
                >
                  <path
                    d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                    clip-rule="evenodd"
                    fill-rule="evenodd"
                  ></path>
                </svg>
              </button>
            </li>
            <li>
              <button
                class="px-3 py-1 text-white transition-colors duration-150 bg-purple-600 border border-r-0 border-purple-600 rounded-md focus:outline-none focus:shadow-outline-purple"
              >
                1
              </button>
            </li>
            <li>
              <button
                class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple"
              >
                2
              </button>
            </li>
            <li>
              <button
                class="px-3 py-1 rounded-md rounded-r-lg focus:outline-none focus:shadow-outline-purple"
                aria-label="Next"
              >
                <svg
                  class="w-4 h-4 fill-current"
                  aria-hidden="true"
                  viewBox="0 0 20 20"
                >
                  <path
                    d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                    clip-rule="evenodd"
                    fill-rule="evenodd"
                  ></path>
                </svg>
              </button>
            </li>
          </ul>
        </nav>
      </span> %>
    </div>
  </div>

  <!-- Charts -->
  <%# <h2
    class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200"
  >
    Charts
  </h2>
  <div class="grid gap-6 mb-8 md:grid-cols-2">
    <div
      class="min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
    >
      <h4 class="mb-4 font-semibold text-gray-800 dark:text-gray-300">
        Revenue
      </h4>
      <canvas id="pie"></canvas>
      <div
        class="flex justify-center mt-4 space-x-3 text-sm text-gray-600 dark:text-gray-400"
      >
        <!-- Chart legend -->
        <div class="flex items-center">
          <span
            class="inline-block w-3 h-3 mr-1 bg-blue-500 rounded-full"
          ></span>
          <span>Shirts</span>
        </div>
        <div class="flex items-center">
          <span
            class="inline-block w-3 h-3 mr-1 bg-teal-600 rounded-full"
          ></span>
          <span>Shoes</span>
        </div>
        <div class="flex items-center">
          <span
            class="inline-block w-3 h-3 mr-1 bg-purple-600 rounded-full"
          ></span>
          <span>Bags</span>
        </div>
      </div>
    </div>
    <div
      class="min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
    >
      <h4 class="mb-4 font-semibold text-gray-800 dark:text-gray-300">
        Traffic
      </h4>
      <canvas id="line"></canvas>
      <div
        class="flex justify-center mt-4 space-x-3 text-sm text-gray-600 dark:text-gray-400"
      >
        <!-- Chart legend -->
        <div class="flex items-center">
          <span
            class="inline-block w-3 h-3 mr-1 bg-teal-600 rounded-full"
          ></span>
          <span>Organic</span>
        </div>
        <div class="flex items-center">
          <span
            class="inline-block w-3 h-3 mr-1 bg-purple-600 rounded-full"
          ></span>
          <span>Paid</span>
        </div>
      </div>
    </div>
  </div> %>
</div>