config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :assertions, except: %i[edit update]
  resources :test_runs
  resources :prompts do
    member do
      get 'diff/:prompt_version_id', action: :diff, as: :diff
    end
  end

  resources :test_runs, except: %i[edit update destroy] do
    resources :test_model_version_runs, only: %i[show] do
      resources :jobs, controller: 'test_model_version_run_jobs', only: %i[create]
    end
  end

  resources :compare, only: [:index] do
    collection do
      get :model_versions
    end
  end

  resources :test_results, only: %i[index update show] do
    resources :assertion_results, only: %i[index]
  end

  resources :models do
    resources :model_versions
  end
  devise_for :users

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'dashboard#index'
end

app/models/prompt.rb
# frozen_string_literal: true

class Prompt < ApplicationRecord
  has_ancestry
  belongs_to :user
  has_many :test_runs, dependent: :destroy
  has_many :test_results, through: :test_runs

  validates :name, presence: true, uniqueness: { scope: :user_id }

  scope :latest_versions, -> { joins("LEFT JOIN prompts AS c ON c.ancestry LIKE CONCAT('%/', prompts.id, '/%')").group('prompts.id').having('COUNT(c.id) = 0') }

  default_scope { order(id: :desc) }
end

app/controllers/prompts_controller.rb
# frozen_string_literal: true

class PromptsController < ApplicationController
  before_action :set_prompt, only: %i[show destroy diff]

  # GET /prompts or /prompts.json
  def index
    @prompts = current_user.prompts.latest_versions
  end

  # GET /prompts/1 or /prompts/1.json
  def show
    @previous_versions = @prompt.ancestors.sort_by { |p| -p.id }
    @latest_version = @prompt.descendants.order(:id).first unless @prompt.childless?
    @test_runs = @prompt.test_runs.includes(model_versions: :model).order(created_at: :desc)
  end

  def edit
    @parent_prompt = current_user.prompts.latest_versions.find(params[:id])
    @prompt = current_user.prompts.new
  end

  def diff
    @previous_prompt_version = current_user.prompts.find(params[:prompt_version_id])
  end

  def update
    parent_prompt = current_user.prompts.find(params[:id])

    @prompt = current_user.prompts.new(prompt_params.merge(parent: parent_prompt))

    respond_to do |format|
      if @prompt.save
        format.html { redirect_to prompt_url(@prompt), notice: 'Prompt was successfully updated.' }
        format.json { render :show, status: :created, location: @prompt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /prompts/new
  def new
    @prompt = current_user.prompts.new
  end

  # POST /prompts or /prompts.json
  def create
    @prompt = current_user.prompts.new(prompt_params)

    respond_to do |format|
      if @prompt.save
        format.html { redirect_to prompt_url(@prompt), notice: 'Prompt was successfully created.' }
        format.json { render :show, status: :created, location: @prompt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prompts/1 or /prompts/1.json
  def destroy
    @prompt.ancestors.destroy_all
    @prompt.destroy!

    respond_to do |format|
      format.html { redirect_to prompts_url, notice: 'Prompt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_prompt
    @prompt = current_user.prompts.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def prompt_params
    params.require(:prompt).permit(:value, :name)
  end
end

app/helpers/prompts_helper.rb
# frozen_string_literal: true

module PromptsHelper
end

app/views/prompts/_form.html.erb
<%= form_with(model: prompt, class: "contents") do |form| %>
  <% if prompt.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(prompt.errors.count, "error") %> prohibited this prompt from being saved:</h2>

      <ul>
        <% prompt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, class: "text-gray-900 dark:text-gray-100" %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :value, class: "text-gray-900 dark:text-gray-100" %>
    <%= form.text_area :value, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    <%= link_to "Back to prompts", prompts_path, class: "ml-2 rounded-lg py-3 px-5 secondary-button inline-block font-medium" %>
  </div>
<% end %>

app/views/prompts/_prompt.html.erb
<div id="<%= dom_id prompt %>">
  <p class="my-5 text-gray-900 dark:text-gray-100">
    <strong class="font-medium mb-1">Name:</strong>
    <%= prompt.name %>
  </p>

  <p class="my-5 text-gray-900 dark:text-gray-100">
    <strong class="font-medium mb-1">Value:</strong>
    <%= prompt.value %>
  </p>

</div>

app/views/prompts/diff.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid">
  <div id="<%= dom_id @prompt %>">
    <p class="my-5 text-gray-900 dark:text-gray-100">
      <strong class="block font-medium mb-1">Value:</strong>
      <%= Diffy::Diff.new(@previous_prompt_version.value, @prompt.value).to_s(:html).html_safe  %>
    </p>
  </div>

  <div class="inline mt-6">
    <%= link_to "Back to prompt", prompt_path(@prompt), class: "rounded-lg py-3 px-5 secondary-button inline-block font-medium" %>
  </div>
</div>

app/views/prompts/edit.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid">
  <h1 class="font-bold text-4xl text-gray-900 dark:text-gray-100">Edit prompt</h1>

  <%= form_with(url: prompt_path(@parent_prompt), method: :patch, class: "contents") do |form| %>
    <% if @prompt.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(@prompt.errors.count, "error") %> prohibited this prompt from being saved:</h2>

        <ul>
          <% @prompt.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :name, class: "text-gray-900 dark:text-gray-100" %>
      <%= form.text_field 'prompt[name]', value: "#{@parent_prompt.name.gsub(/ Version \d+/, '')} Version #{@parent_prompt.ancestor_ids.size + 2}", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :value, class: "text-gray-900 dark:text-gray-100" %>
      <%= form.text_area 'prompt[value]', value: @parent_prompt.value, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
      <%= link_to "Back to prompt", prompt_path(@parent_prompt), class: "ml-2 rounded-lg py-3 px-5 secondary-button inline-block font-medium" %>
    </div>
  <% end %>
</div>

app/views/prompts/index.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid">
  <%= render 'layouts/flash' %>

  <% content_for :title, "Prompts" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl text-gray-900 dark:text-gray-100">Prompts</h1>
    <div class="flex space-x-4">
       <%= link_to "New prompt", new_prompt_path, class: "px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" %>
    </div>
  </div>

  <div class="w-full overflow-hidden rounded-lg shadow-xs mx-auto mt-10 w-full">
    <div class="w-full overflow-x-auto">
      <table class="w-full whitespace-no-wrap">
        <thead>
          <tr
            class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800"
          >
            <th class="px-4 py-3">Name</th>
            <th class="px-4 py-3">Created At</th>
          </tr>
        </thead>
        <tbody
          class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800"
        >
          <% if @prompts.empty? %>
            <tr>
              <td colspan="2" class="px-4 py-3 text-center">
                <p class="text-gray-500">No prompts found.</p>
              </td>
            </tr>
          <% else %>
            <% @prompts.each do |prompt| %>
              <tr class="text-gray-700 dark:text-gray-400">
                <td class="px-4 py-3 text-sm">
                  <p class="font-semibold"><%= link_to prompt.name, prompt, class: "text-blue-500 underline-link" %></p>
                </td>
                <td class="px-4 py-3 text-sm">
                  <%= prompt.created_at.to_date %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/prompts/new.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid">
  <h1 class="font-bold text-4xl text-gray-900 dark:text-gray-100">New prompt</h1>

  <%= render "form", prompt: @prompt %>
</div>

app/views/prompts/show.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid">
  <%= render 'layouts/flash' %>

  <%= render @prompt %>

  <div class="inline">
    <% if @prompt.childless? %>
      <%= link_to "Back to prompts", prompts_path, class: "rounded-lg py-3 px-5 secondary-button inline-block font-medium" %>
    <% else %>
      <%= link_to "Back to latest version", prompt_path(@latest_version), class: "rounded-lg py-3 px-5 secondary-button inline-block font-medium" %>
    <% end %>
    <%= link_to "Create test runs", new_test_run_path(prompt_id: @prompt), class: "ml-2 rounded-lg py-3 px-5 secondary-button inline-block font-medium" %>
    <% if @prompt.childless? %>
      <%= link_to "Edit this prompt", edit_prompt_path(@prompt), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2">
        <%= button_to "Destroy this prompt", @prompt, method: :delete, class: "mt-2 rounded-lg py-3 px-5 delete-button font-medium" %>
      </div>
    <% end %>
  </div>

  <div class="w-full w-full mx-auto mt-10 overflow-hidden rounded-lg shadow-xs">
    <h1 class="font-bold text-4xl text-gray-900 dark:text-gray-100">Test Runs</h1>
    <div class="w-full overflow-x-auto">
      <table class="w-full whitespace-no-wrap">
        <thead>
          <tr
            class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800"
          >
            <th class="px-4 py-3">ID</th>
            <th class="px-4 py-3">Name</th>
            <th class="px-4 py-3">Models</th>
            <th class="px-4 py-3">Created at</th>
          </tr>
        </thead>
        <tbody
          class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800"
        >
          <% if @test_runs.empty? %>
            <tr>
              <td colspan="7" class="px-4 py-3 text-center">
                <p class="text-gray-500">No test runs found.</p>
              </td>
            </tr>
          <% else %>
            <% @test_runs.each do |test_run| %>
              <tr class="text-gray-700 dark:text-gray-400">
                <td class="px-4 py-3 text-sm">
                  <p class="font-semibold"><%= link_to test_run.id, test_run, class: "text-blue-500 underline-link" %></p>
                </td>
                <td class="px-4 py-3 text-sm">
                  <p class="font-semibold"><%= test_run.name %></p>
                </td>
                <td class="px-4 py-3 text-sm">
                  <p class="font-semibold"><%= test_run.model_versions.map(&:full_name).join(', ') %></p>
                </td>
                <td class="px-4 py-3 text-sm">
                  <%= time_ago_in_words(test_run.created_at) %> ago
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <% if @previous_versions.present? %>
    <div class="w-full overflow-hidden rounded-lg shadow-xs mx-auto mt-10 w-full">
      <h1 class="font-bold text-4xl text-gray-900 dark:text-gray-100">Previous Versions</h1>
      <div class="w-full overflow-x-auto">
        <table class="w-full whitespace-no-wrap">
          <thead>
            <tr
              class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800"
            >
              <th class="px-4 py-3">Name</th>
              <th class="px-4 py-3">Created At</th>
              <th class="px-4 py-3"></th>
            </tr>
          </thead>
          <tbody
            class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800"
          >
            <% @previous_versions.each do |prompt| %>
              <tr class="text-gray-700 dark:text-gray-400">
                <td class="px-4 py-3 text-sm">
                  <p class="font-semibold"><%= link_to prompt.name, prompt, class: "text-blue-500 underline-link" %></p>
                </td>
                <td class="px-4 py-3 text-sm">
                  <%= prompt.created_at.to_date %>
                </td>
                <td class="px-4 py-3 text-sm">
                  <%= link_to 'Show diff', diff_prompt_path(@prompt, prompt), class: "text-blue-500 underline-link" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</div>