config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :assertions, except: %i[edit update]
  resources :test_runs
  resources :prompts do
    member do
      get 'diff/:prompt_version_id', action: :diff, as: :diff
    end
  end

  resources :test_runs, except: %i[edit update destroy] do
    resources :test_model_version_runs, only: %i[show] do
      resources :jobs, controller: 'test_model_version_run_jobs', only: %i[create]
    end
  end

  resources :compare, only: [:index] do
    collection do
      get :model_versions
    end
  end

  resources :test_results, only: %i[index update show] do
    resources :assertion_results, only: %i[index]
  end

  resources :models do
    resources :model_versions
  end
  devise_for :users

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'dashboard#index'
end

app/models/model_version.rb
# frozen_string_literal: true

class ModelVersion < ApplicationRecord
  belongs_to :model
  has_many :test_model_version_runs, dependent: :destroy
  has_many :test_results, through: :test_model_version_runs
  has_many :assertions, dependent: :destroy
  validate :configuration_is_json
  before_save :parse_configuration
  delegate :executor_type, to: :model
  delegate :api_key, to: :model

  default_scope { order(id: :desc) }

  def as_json(options = {})
    options[:methods] ||= [:full_name]
    super
  end

  def full_name
    "#{model.name} #{build_name}"
  end

  def content_path
    CONTENT_PATHS[executor_type]
  end

  private

  CONTENT_PATHS = {
    'openai' => ['choices', 0, 'message', 'content'],
    'ollama' => [0, 'response'],
    'llama_cpp' => ['content']
  }.freeze

  def configuration_is_json
    return unless configuration.present? && !configuration.is_a?(Hash)

    JSON.parse(configuration)
  rescue JSON::ParserError
    errors.add(:configuration, 'must be valid JSON')
  end

  def parse_configuration
    self.configuration = JSON.parse(configuration) if configuration.is_a?(String) && !configuration.empty?
  end
end

app/controllers/model_versions_controller.rb
# frozen_string_literal: true

class ModelVersionsController < ApplicationController
  before_action :set_model
  before_action :set_model_version, only: %i[show edit update destroy]

  # GET /model_versions or /model_versions.json
  def index
    @model_versions = @model.model_versions
  end

  # GET /model_versions/1 or /model_versions/1.json
  def show; end

  # GET /model_versions/new
  def new
    @model_version = @model.model_versions.new
  end

  # GET /model_versions/1/edit
  def edit; end

  # POST /model_versions or /model_versions.json
  def create
    @model_version = @model.model_versions.new(model_version_params)

    respond_to do |format|
      if @model_version.save
        format.html do
          redirect_to model_model_version_url(@model, @model_version), notice: 'Model version was successfully created.'
        end
        format.json { render :show, status: :created, location: model_model_version_url(@model, @model_version) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @model_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /model_versions/1 or /model_versions/1.json
  def update
    respond_to do |format|
      if @model_version.update(model_version_params)
        format.html do
          redirect_to model_model_version_url(@model, @model_version), notice: 'Model version was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @model_version }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @model_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /model_versions/1 or /model_versions/1.json
  def destroy
    @model_version.destroy!

    respond_to do |format|
      format.html { redirect_to model_model_versions_url(@model), notice: 'Model version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_model_version
    @model_version = @model.model_versions.find(params[:id])
  end

  def set_model
    @model = current_user.models.find(params[:model_id])
  end

  # Only allow a list of trusted parameters through.
  def model_version_params
    params.require(:model_version).permit(:configuration, :description, :built_on, :build_name)
  end
end

app/helpers/model_versions_helper.rb
# frozen_string_literal: true

module ModelVersionsHelper
  DEFAULT_CONFIGURATION = {
    'openai' => '{"model":"gpt-3.5-turbo","temperature":0.5}',
    'ollama' => '{"model":"llama3.1", "stream": false}',
    'llama_cpp' => '{"n_predict":500,"temperature":0.5,"stop":["<|end|>","<|user|>","<|assistant|>","<|endoftext|>","<|system|>"]}'
  }.freeze

  def default_configuration(executor_type)
    DEFAULT_CONFIGURATION[executor_type] || {}.to_json
  end
end

app/views/model_versions/_form.html.erb
<%= form_with(model: [@model, model_version], class: "contents") do |form| %>
  <% if model_version.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(model_version.errors.count, "error") %> prohibited this model_version from being saved:</h2>

      <ul>
        <% model_version.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :configuration, class: "text-gray-900 dark:text-gray-100" %>
    <%= form.text_field :configuration, value: model_version&.configuration ? JSON::dump(model_version&.configuration) : default_configuration(@model.executor_type), class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description, class: "text-gray-900 dark:text-gray-100" %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :built_on, class: "text-gray-900 dark:text-gray-100" %>
    <%= form.date_field :built_on, value: model_version&.built_on || Date.today, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :build_name, class: "text-gray-900 dark:text-gray-100" %>
    <%= form.text_field :build_name, value: model_version&.build_name || "Version #{ @model.model_versions.count + 1 }", class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    <% unless @model_version.new_record? %>
      <%= link_to "Show this model version", [@model, @model_version], class: "ml-2 rounded-lg py-3 px-5 secondary-button inline-block font-medium" %>
    <% end %>
    <%= link_to "Back to model", model_path(@model), class: "ml-2 rounded-lg py-3 px-5 secondary-button inline-block font-medium" %>
  </div>
<% end %>

app/views/model_versions/_model_version.html.erb
<div id="<%= dom_id model_version %>">
  <p class="my-5 text-gray-900 dark:text-gray-100">
    <strong class="font-medium mb-1">Model:</strong>
    <%= @model&.name %>
  </p>

  <p class="my-5 text-gray-900 dark:text-gray-100">
    <strong class="font-medium mb-1">Configuration:</strong>
    <pre id="json-display" class="ext-gray-900 dark:text-gray-100"></pre>
  </p>

  <p class="my-5 text-gray-900 dark:text-gray-100">
    <strong class="font-medium mb-1">Description:</strong>
    <%= model_version.description %>
  </p>

  <p class="my-5 text-gray-900 dark:text-gray-100">
    <strong class="font-medium mb-1">Built on:</strong>
    <%= model_version.built_on&.to_date || 'not specified' %>
  </p>

  <p class="my-5 text-gray-900 dark:text-gray-100">
    <strong class="font-medium mb-1">Build name:</strong>
    <%= model_version.build_name %>
  </p>

</div>

<script>
  var jsonData = <%= raw model_version.configuration&.to_json || '{}' %>;
  document.getElementById('json-display').textContent = JSON.stringify(jsonData, null, 2);
</script>

app/views/model_versions/edit.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid">
  <h1 class="font-bold text-4xl text-gray-900 dark:text-gray-100">Editing model version</h1>

  <%= render "form", model_version: @model_version %>
</div>

app/views/model_versions/index.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid">
  <%= render 'layouts/flash' %>

  <% content_for :title, "Model versions" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl text-gray-900 dark:text-gray-100">Model versions</h1>
    <%= link_to "New model version", new_model_model_version_path(@model), class: "px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" %>
  </div>

  <div class="w-full overflow-hidden rounded-lg shadow-xs">
    <div class="w-full overflow-x-auto">
      <table class="w-full whitespace-no-wrap">
        <thead>
          <tr
            class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800"
          >
            <th class="px-4 py-3">Build name</th>
            <th class="px-4 py-3">Model</th>
            <th class="px-4 py-3">Built on</th>
          </tr>
        </thead>
        <tbody
          class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800"
        >
          <% if @model_versions.empty? %>
            <tr>
              <td colspan="3" class="px-4 py-3 text-center">
                <p class="text-gray-500">No versions found.</p>
              </td>
            </tr>
          <% else %>
            <% @model_versions.each do |model_version| %>
              <tr class="text-gray-700 dark:text-gray-400">
                <td class="px-4 py-3 text-sm">
                  <p class="font-semibold"><%= link_to model_version.build_name, [@model, model_version], class: "text-blue-500 underline-link" %></p>
                </td>
                <td class="px-4 py-3">
                  <div class="flex items-center text-sm">
                    <div>
                      <p class="font-semibold"><%= link_to @model.name, @model, class: "text-blue-500 underline-link" %></p>
                    </div>
                  </div>
                </td>
                <td class="px-4 py-3 text-sm">
                  <%= model_version.built_on&.to_date || 'not specified' %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/model_versions/new.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid">
  <h1 class="font-bold text-4xl text-gray-900 dark:text-gray-100">New model version</h1>

  <%= render "form", model_version: @model_version %>
</div>

app/views/model_versions/show.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid">
  <%= render 'layouts/flash' %>

  <%= render @model_version %>

  <div class="inline" >
    <%= link_to "Edit this model version", edit_model_model_version_path(@model, @model_version), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to model", model_path(@model), class: "ml-2 rounded-lg py-3 px-5 secondary-button inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this model version", [@model, @model_version], method: :delete, class: "mt-2 rounded-lg py-3 px-5 delete-button font-medium" %>
    </div>
  </div>
</div>