config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :assertions, except: %i[edit update]
  resources :test_runs
  resources :prompts do
    member do
      get 'diff/:prompt_version_id', action: :diff, as: :diff
    end
  end

  resources :test_runs, except: %i[edit update destroy] do
    resources :test_model_version_runs, only: %i[show] do
      resources :jobs, controller: 'test_model_version_run_jobs', only: %i[create]
    end
  end

  resources :compare, only: [:index] do
    collection do
      get :model_versions
    end
  end

  resources :test_results, only: %i[index update show] do
    resources :assertion_results, only: %i[index]
  end

  resources :models do
    resources :model_versions
  end
  devise_for :users

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'dashboard#index'
end

app/models/test_run.rb
# frozen_string_literal: true

class TestRun < ApplicationRecord
  belongs_to :prompt
  has_many :test_model_version_runs, dependent: :destroy
  has_many :model_versions, through: :test_model_version_runs
  has_many :test_results, through: :test_model_version_runs
  has_and_belongs_to_many :assertions

  accepts_nested_attributes_for :test_model_version_runs, allow_destroy: true

  default_scope { order(id: :desc) }
end

app/controllers/test_runs_controller.rb
# frozen_string_literal: true

class TestRunsController < ApplicationController
  before_action :set_test_run, only: %i[show]

  # GET /test_runs or /test_runs.json
  def index
    @test_runs = current_user.test_runs.includes(model_versions: :model).all

    @test_runs = @test_runs.where(prompt_id: params[:prompt_id]) if params[:prompt_id].present?
  end

  # GET /test_runs/1 or /test_runs/1.json
  def show
    @latest_prompt_version = @test_run.prompt.descendants.order(:id).first
    @test_model_version_runs = @test_run.test_model_version_runs.includes(:test_results, model_version: :model).with_passed_test_results_count.decorate
  end

  # GET /test_runs/new
  def new
    @prompt = current_user.prompts.find_by(id: params[:prompt_id])
    @prompts = current_user.prompts.latest_versions
    @ancestor_prompts = Prompt.where(id: @prompts.map(&:ancestor_ids).flatten)
    @model_versions = current_user.model_versions.includes(:model)
    @assertions = current_user.assertions
    @test_run = current_user.test_runs.new(prompt: @prompt)
  end

  # POST /test_runs or /test_runs.json
  def create
    @test_run = current_user.test_runs.new(test_run_params)

    respond_to do |format|
      if @test_run.save
        TestRunJob.perform_later(@test_run.id) unless manual_execution?
        format.html { redirect_to test_run_url(@test_run), notice: 'Test model version run was successfully created.' }
        format.json { render :show, status: :created, location: @test_run }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @test_run.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_test_run
    @test_run = current_user.test_runs.find(params[:id])
  end

  def manual_execution?
    ActiveModel::Type::Boolean.new.cast(params.dig(:test_run, :manual_execution))
  end

  # Only allow a list of trusted parameters through.
  def test_run_params
    params.require(:test_run).permit(:name, :prompt_id, :calls, :passing_threshold, assertion_ids: []).tap do |permited|
      model_version_ids = params[:test_run][:model_version_ids]&.select(&:present?)
      if model_version_ids.present?
        permited[:test_model_version_runs_attributes] = model_version_ids.map do |model_version_id|
          { model_version_id: }
        end
      end
    end
  end
end

app/helpers/test_runs_helper.rb
# frozen_string_literal: true

module TestRunsHelper
end

app/views/test_runs/_form.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid">
  <%= form_for(test_run, class: "contents") do |form| %>
    <% if test_run.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(test_run.errors.count, "error") %> prohibited this test run from being saved:</h2>

        <ul>
          <% test_run.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :name, class: "text-gray-900 dark:text-gray-100" %>
      <%= form.text_field :name, value: test_run&.name || Time.zone.now.strftime("%b %d, %Y %I:%M %p"), class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :prompt_id, class: "text-gray-900 dark:text-gray-100" %>
      <%= form.select :prompt_id, grouped_options_for_select(options_with_versions(@prompts, @ancestor_prompts), @prompt&.id), {}, { class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" } %>
    </div>
    <div class="my-5">
      <%= form.label :calls, class: "text-gray-900 dark:text-gray-100" %>
      <%= form.number_field :calls, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= form.label :assertions, class: "text-gray-900 dark:text-gray-100" %>
      <%= form.collection_select :assertion_ids, @assertions, :id, :name, {}, { multiple: true, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" } %>
    </div>
    <div class="my-5">
      <%= form.label :model_versions, class: "text-gray-900 dark:text-gray-100" %>
      <%= form.collection_select :model_version_ids, @model_versions, :id, :full_name, {}, { multiple: true, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" } %>
    </div>
    <div class="my-5">
      <%= form.label 'Passing threshold in %', class: "text-gray-900 dark:text-gray-100" %>
      <%= form.number_field :passing_threshold, step: '0.01', max: 100, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
      <%= label_tag do %>
        <%= check_box_tag 'test_run[manual_execution]' %>
        Manual execution
      <% end %>
    </div>

    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
      <% if @prompt.present? %>
        <%= link_to "Back to prompt", prompt_path(@prompt), class: "ml-2 rounded-lg py-3 px-5 secondary-button inline-block font-medium" %>
      <% else %>
        <%= link_to "Back to test runs", test_runs_path, class: "ml-2 rounded-lg py-3 px-5 secondary-button inline-block font-medium" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/test_runs/_test_run.html.erb
<div id="<%= dom_id test_run %>">
  <p class="my-5 text-gray-900 dark:text-gray-100">
    <strong class="font-medium mr-2">Name:</strong> <%= test_run.name %>
  </p>
  <p class="my-5 text-gray-900 dark:text-gray-100">
    <strong class="font-medium mr-2">Calls:</strong> <%= test_run.calls %>
  </p>
  <p class="my-5 text-gray-900 dark:text-gray-100">
   <strong class="font-medium mr-2">Prompt:</strong> <%= link_to test_run.prompt.name, test_run.prompt, class: "text-blue-500 underline-link" %>
  </p>

  <% if @latest_prompt_version.present? %>
    <div class="inline-block ml-2">
      <%= button_to "Rerun with latest prompt version", test_runs_path, params: { test_run: { name: "#{test_run.name} ", calls: test_run.calls, assertion_ids: test_run.assertion_ids, passing_threshold: test_run.passing_threshold, model_version_ids: test_run.model_version_ids, prompt_id: @latest_prompt_version } }, class: "mt-2 rounded-lg py-3 px-5 secondary-button font-medium" %>
    </div>
  <% end %>
</div>

app/views/test_runs/index.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid">
  <%= render 'layouts/flash' %>

  <% content_for :title, "Test Runs" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl text-gray-900 dark:text-gray-100">Test Runs</h1>
     <div class="flex space-x-4">
       <%= link_to "New test run", new_test_run_path, class: "px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" %>
    </div>
  </div>

  <div class="w-full w-full mx-auto mt-10 overflow-hidden rounded-lg shadow-xs">
    <div class="w-full overflow-x-auto">
      <table class="w-full whitespace-no-wrap">
        <thead>
          <tr
            class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800"
          >
            <th class="px-4 py-3">ID</th>
            <th class="px-4 py-3">Name</th>
            <th class="px-4 py-3">Models</th>
            <th class="px-4 py-3">Created at</th>
          </tr>
        </thead>
        <tbody
          class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800"
        >
          <% if @test_runs.empty? %>
            <tr>
              <td colspan="7" class="px-4 py-3 text-center">
                <p class="text-gray-500">No test runs found.</p>
              </td>
            </tr>
          <% else %>
            <% @test_runs.each do |test_run| %>
              <tr class="text-gray-700 dark:text-gray-400">
                <td class="px-4 py-3 text-sm">
                  <p class="font-semibold"><%= link_to test_run.id, test_run, class: "text-blue-500 underline-link" %></p>
                </td>
                <td class="px-4 py-3 text-sm">
                  <p class="font-semibold"><%= test_run.name %></p>
                </td>
                <td class="px-4 py-3 text-sm">
                  <p class="font-semibold"><%= test_run.model_versions.map(&:full_name).join(', ') %></p>
                </td>
                <td class="px-4 py-3 text-sm">
                  <%= time_ago_in_words(test_run.created_at) %> ago
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/test_runs/new.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid">
  <h1 class="font-bold text-4xl text-gray-900 dark:text-gray-100">New test run</h1>

  <%= render "form", test_run: @test_run %>
</div>

app/views/test_runs/show.html.erb
<div class="container px-6 mx-auto mt-10 mb-10 grid">
  <%= render 'layouts/flash' %>

  <%= render @test_run %>

  <div class="w-full w-full mx-auto mt-10 overflow-hidden rounded-lg shadow-xs">
    <h1 class="font-bold text-4xl text-gray-900 dark:text-gray-100">Models Runs</h1>
    <div class="w-full overflow-x-auto">
      <table class="w-full whitespace-no-wrap">
        <thead>
          <tr
            class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800"
          >
            <th class="px-4 py-3">ID</th>
            <th class="px-4 py-3">Model</th>
            <th class="px-4 py-3">Model Version</th>
            <th class="px-4 py-3">State</th>
            <th class="px-4 py-3">Created at</th>
            <% if @test_model_version_runs.any?(&:pending?) %>
              <th class="w-1"></th>
            <% end %>
          </tr>
        </thead>
        <tbody
          class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800"
        >
          <% if @test_model_version_runs.empty? %>
            <tr>
              <td colspan="5" class="px-4 py-3 text-center">
                <p class="text-gray-500">No model versions runs found.</p>
              </td>
            </tr>
          <% else %>
            <% @test_model_version_runs.each do |test_model_version_run| %>
              <tr class="text-gray-700 dark:text-gray-400">
                <td class="px-4 py-3 text-sm">
                  <p class="font-semibold"><%= link_to test_model_version_run.id, [@test_run, test_model_version_run], class: "text-blue-500 underline-link" %></p>
                </td>
                <td class="px-4 py-3 text-sm">
                  <p class="font-semibold"><%= link_to test_model_version_run.model_version.model.name, test_model_version_run.model_version.model, class: "text-blue-500 underline-link" %></p>
                </td>
                <td class="px-4 py-3 text-sm">
                  <p class="font-semibold"><%= link_to test_model_version_run.model_version.build_name, [test_model_version_run.model_version.model, test_model_version_run.model_version], class: "text-blue-500 underline-link" %></p>
                </td>
                <td class="px-4 py-3 text-xs">
                  <% state = test_model_version_run.state %>
                  <span
                    class="px-2 py-1 font-semibold leading-tight rounded-full <%= define_status_class(state) %>"
                  >
                     <%= state.capitalize %> <%= test_model_version_run.passed_percentage.present? ? "(#{test_model_version_run.passed_percentage})%" : '' %>
                  </span>
                </td>
                <td class="px-4 py-3 text-sm">
                  <%= time_ago_in_words(test_model_version_run.created_at) %> ago
                </td>
                <% if test_model_version_run.pending? %>
                  <td class="px-4 py-2">
                    <%= button_to 'Run', test_run_test_model_version_run_jobs_path(@test_run, test_model_version_run), method: :post, class: 'bg-blue-500 text-white font-bold py-2 px-4 rounded' %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>